while (true) {
    pins.analogWritePin(AnalogPin.P0, 50)
    pins.analogWritePin(AnalogPin.P0, 100)
    pins.analogWritePin(AnalogPin.P0, 150)
    pins.analogWritePin(AnalogPin.P0, 200)
    pins.analogWritePin(AnalogPin.P0, 250)
    pins.analogWritePin(AnalogPin.P0, 300)
    pins.analogWritePin(AnalogPin.P0, 350)
    pins.analogWritePin(AnalogPin.P0, 400)
    pins.analogWritePin(AnalogPin.P0, 450)
    pins.analogWritePin(AnalogPin.P0, 500)
    pins.analogWritePin(AnalogPin.P0, 550)
    pins.analogWritePin(AnalogPin.P0, 600)
    pins.analogWritePin(AnalogPin.P0, 650)
    pins.analogWritePin(AnalogPin.P0, 700)
    pins.analogWritePin(AnalogPin.P0, 750)
    pins.analogWritePin(AnalogPin.P0, 800)
    pins.analogWritePin(AnalogPin.P0, 850)
    pins.analogWritePin(AnalogPin.P0, 900)
    pins.analogWritePin(AnalogPin.P0, 950)
    pins.analogWritePin(AnalogPin.P0, 1000)
    pins.analogWritePin(AnalogPin.P0, 950)
    pins.analogWritePin(AnalogPin.P0, 900)
    pins.analogWritePin(AnalogPin.P0, 850)
    pins.analogWritePin(AnalogPin.P0, 800)
    pins.analogWritePin(AnalogPin.P0, 750)
    pins.analogWritePin(AnalogPin.P0, 700)
    pins.analogWritePin(AnalogPin.P0, 650)
    pins.analogWritePin(AnalogPin.P0, 600)
    pins.analogWritePin(AnalogPin.P0, 550)
    pins.analogWritePin(AnalogPin.P0, 500)
    pins.analogWritePin(AnalogPin.P0, 450)
    pins.analogWritePin(AnalogPin.P0, 400)
    pins.analogWritePin(AnalogPin.P0, 350)
    pins.analogWritePin(AnalogPin.P0, 300)
    pins.analogWritePin(AnalogPin.P0, 250)
    pins.analogWritePin(AnalogPin.P0, 200)
    pins.analogWritePin(AnalogPin.P0, 150)
    pins.analogWritePin(AnalogPin.P0, 100)
    pins.analogWritePin(AnalogPin.P0, 50)

}
//I hardcoded it because I could do it with math functions but I guess I was on the wrong path to make it work correctly :( 
//after trying for 30mins I just kind of decided to hardcode it and move on
